apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: check-db-readiness
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresql.port | quote }}
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URI
                  name: {{ .Chart.Name }}-secret
            - name: APP_PORT
              value: {{ .Values.deployment.pod.port | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: {{ .Chart.Name }}-secret
            - name: KAFKA_HOST
              value: {{ .Values.kafka.dns }}
            - name: BILLING_SERVICE
              value: {{ .Values.external.billing }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.pod.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 2
            periodSeconds: 2